name: Deploy to Pinata

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.6
      with:
        path: "./dapp"
        pinataKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
        pinataPinName: "TokenVesting"
